FROM php:8.3-fpm

# Extensions PHP nécessaires
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    libicu-dev \
    unzip \
    && docker-php-ext-install \
    pdo_pgsql \
    zip \
    intl \
    && rm -rf /var/lib/apt/lists/*

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Copier les fichiers de configuration d'abord
COPY composer.json composer.lock symfony.lock ./

# Installer les dépendances sans scripts
RUN composer install --no-scripts --no-autoloader

# Copier tout le reste du code
COPY . .
RUN composer require hwi/oauth-bundle --no-scripts

# Générer l'autoloader et exécuter les scripts maintenant que tout est copié
RUN composer dump-autoload --optimize && composer run-script post-install-cmd

# Assurer les bonnes permissions pour var/
RUN chown -R www-data:www-data /var/www/html/var && \
    chmod -R 755 /var/www/html/var && \
    chown -R www-data:www-data /var/www/html/config && \
    chmod -R 755 /var/www/html/config