CREATE TABLE "accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "username" varchar(30),
  "email" varchar(100),
  "password" varchar(255),
  "avatar_url" varchar(255),
  "bio" text,
  "role" varchar(20),
  "is_verified" boolean,
  "is_banned" boolean,
  "ban_reason" text,
  "reset_password_token" varchar(255),
  "reset_token_expires_at" datetime,
  "created_at" datetime
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "created_at" datetime
);

CREATE TABLE "templates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "type" varchar(50),
  "content" text,
  "created_at" datetime
);

CREATE TABLE "conversations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(100),
  "description" text,
  "category_id" int,
  "creator_id" int,
  "created_at" datetime,
  "updated_at" datetime,
  "views" int,
  "is_public" boolean,
  "status" enum(draft,published),
  "interlocutor_name" varchar(50),
  "interlocutor_username" varchar(30),
  "interlocutor_avatar_url" varchar(255),
  "start_time" time,
  "battery_level" int,
  "network_type" varchar(20),
  "signal_quality" varchar(20),
  "template_id" int
);

CREATE TABLE "messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" int,
  "status" enum(draft,published),
  "sender" enum(user,interlocutor),
  "content" json,
  "type" enum(text,emoji,image,video),
  "image_url" BLOB,
  "video_url" BLOB,
  "timestamp" datetime,
  "updated_at" datetime,
  "template_id" int
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" int,
  "user_id" int,
  "content" text,
  "created_at" datetime,
  "parent_comment_id" int
);

CREATE TABLE "favorites" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "conversation_id" int,
  "created_at" datetime
);

CREATE TABLE "likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "message_id" int,
  "created_at" datetime
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subscription_id" int,
  "amount" decimal(10,2),
  "payment_method" varchar(50),
  "status" enum(pending,completed,failed),
  "created_at" datetime
);

CREATE TABLE "invoices" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subscription_id" int,
  "invoice_number" varchar(255),
  "issued_date" datetime
);

CREATE TABLE "contacts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "email" varchar(100),
  "subject" varchar(100),
  "message" text,
  "created_at" datetime
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "type" varchar(50),
  "message" text,
  "is_read" boolean,
  "created_at" datetime
);

CREATE TABLE "topics" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "title" varchar(100),
  "content" text,
  "image_url" BLOB,
  "conversation_id" int,
  "created_at" datetime
);

CREATE TABLE "topics_comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topics_id" int,
  "user_id" int,
  "content" text,
  "parent_comment_id" int,
  "created_at" datetime
);

CREATE TABLE "subscriptions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "plan_id" int,
  "start_date" datetime,
  "end_date" datetime,
  "status" enum(active,expired,canceled)
);

CREATE TABLE "plans" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "price" decimal(10,2),
  "features" text,
  "created_at" datetime
);

CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30)
);

CREATE TABLE "conversation_tags" (
  "conversation_id" int,
  "tag_id" int,
  PRIMARY KEY ("conversation_id", "tag_id")
);

CREATE TABLE "reports" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reported_by_user_id" int,
  "target_type" varchar(20),
  "target_id" int,
  "reason" text,
  "status" varchar(20),
  "created_at" datetime
);

ALTER TABLE "conversations" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "conversations" ADD FOREIGN KEY ("creator_id") REFERENCES "accounts" ("id");

ALTER TABLE "conversations" ADD FOREIGN KEY ("template_id") REFERENCES "templates" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("template_id") REFERENCES "templates" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("parent_comment_id") REFERENCES "comments" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("subscription_id") REFERENCES "subscriptions" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("subscription_id") REFERENCES "subscriptions" ("id");

ALTER TABLE "contacts" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("id");

ALTER TABLE "topics" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("id");

ALTER TABLE "topics" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id");

ALTER TABLE "topics_comments" ADD FOREIGN KEY ("topics_id") REFERENCES "topics" ("id");

ALTER TABLE "topics_comments" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("id");

ALTER TABLE "topics_comments" ADD FOREIGN KEY ("parent_comment_id") REFERENCES "topics_comments" ("id");

ALTER TABLE "subscriptions" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("id");

ALTER TABLE "subscriptions" ADD FOREIGN KEY ("plan_id") REFERENCES "plans" ("id");

ALTER TABLE "conversation_tags" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id");

ALTER TABLE "conversation_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");

ALTER TABLE "reports" ADD FOREIGN KEY ("reported_by_user_id") REFERENCES "accounts" ("id");
