services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: talkLabs_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/:rw
      - ./logs/nginx:/var/log/nginx/:rw
    depends_on:
      - php
    networks:
      - networks_talkLabs

  php:
    build:
      context: ./docker/php
    container_name: talkLabs_php
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    networks:
      - networks_talkLabs
    environment:
      DATABASE_URL: "postgresql://root:root@database:5432/app?serverVersion=16&charset=utf8"
  
  database:
    image: postgres:16-alpine
    container_name: talkLabs_database
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: root
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "root"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - networks_talkLabs
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: talkLabs_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - networks_talkLabs

volumes:
  database_data:

networks:
  networks_talkLabs:
    driver: bridge